FROM ubuntu:16.04

RUN apt-get update

RUN apt-get install -y curl

RUN apt-get install sudo -y

RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

RUN apt-get install -y nodejs

RUN nodejs -v

RUN mkdir /usr/share/app

WORKDIR /usr/share/app

COPY . .

CMD nodejs index.js
